### PR TITLE
Match chrome version by default

### LINKED ISSUE #2: Match version of the chrome by default
I'd like to use this action but hardcoding the version does not sound like a scalable option. Would it make sense to auto-determine the version by default?

```sh
CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1)
CHROME_DRIVER_VERSION=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
```

### PR DESCRIPTION
**Pull request by krasnoukhov**
Fixes #2

### CODE REVIEW

File: lib/setup-chromedriver.sh [hunk 1]
```diff
@@ -2,11 +2,14 @@
 
 set -eo pipefail
 
-version=$1
-arch=$2
+VERSION=$1
+ARCH=$2
 
-sudo apt-fast install -y xvfb screen google-chrome-stable
```
Comment (krasnoukhov) [inline lib/setup-chromedriver.sh]: I'm removing this since it's included by default: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

**Comment by nanasess** [comment]
@krasnoukhov Merged,  Thanks for the feedback. 👍
